#ifndef __GINSENG_SMC_CMD_H
#define __GINSENG_SMC_CMD_H

// DON'T MODIFY THE TWO COMMENT LINES: 'MAGIC_START' AND 'MAGIC_END'
// DON'T USE SURFIX THAT RUST CANNOT UNDERSTAND SUCH AS 'UL'

// MAGIC_START
#define GINSENG_SMC_CMD_PING					0xFFFF
#define GINSENG_SMC_CMD_NULL					0xFFFE
#define GINSENG_SMC_CMD_RS_NULL					0xFFFD

#define GINSENG_SMC_CMD_COPY_PAGE 				0x7900
#define GINSENG_SMC_CMD_COPY_PAGE_TEST 			0x7901
#define GINSENG_SMC_CMD_COPY_PAGE_TEST_CMP_IN_K	0x7902

#define GINSENG_SMC_CMD_CLEAR_PAGE 									0x7910
#define GINSENG_SMC_CMD_CLEAR_PAGE_TEST_CLEAR_IN_EL1_CHECK_IN_EL3	0x7911
#define GINSENG_SMC_CMD_CLEAR_PAGE_TEST_CLEAR_IN_EL3_CHECK_IN_EL1	0x7912

#define GINSENG_SMC_CMD_USER_VADDR_TO_PADDR								0x7913

#define GINSENG_SMC_CMD_SET_64BIT									0x7920
#define GINSENG_SMC_CMD_SET_64BIT_DCI								0x7921

#define GINSENG_SMC_CMD_RS_PING										0xA000
#define GINSENG_SMC_CMD_RS_INIT										0xA001

#define GINSENG_SMC_CMD_TEST 							0xFFFF000000000000
#define GINSENG_SMC_CMD_TEST_SSECTION_ENTRY				(GINSENG_SMC_CMD_TEST | 0x0001)
#define GINSENG_SMC_CMD_TEST_PT_WALK					(GINSENG_SMC_CMD_TEST | 0x0002)

#define GINSENG_UUID_QEMU_TEST		0xFFFF
// MAGIC_END

#ifndef __ASSEMBLY__
#define dc_invalidate_single(addr)	\
	asm volatile (					\
		"dc ivac, %0\n"		\
		"dmb sy\n"					\
		"isb sy"					\
		:							\
		: "r" (addr)			\
		:							\
		)
#endif
#endif