#ifndef __GINSENG_H
#define __GINSENG_H

#define GINSENG_COPY_PAGE_IN_EL3 						0x7700
#define GINSENG_RS_INIT									0x8800

#define GINSENG_TEST 									0xAA000000
#define GINSENG_TEST_TOGGLE_TRACE_FAULT					(GINSENG_TEST | 0x8877)

#define GINSENG_TEST_COPY_PAGE_CP_IN_EL1_CMP_IN_EL3		(GINSENG_TEST | 0x8878)
#define GINSENG_TEST_COPY_PAGE_CP_IN_EL3_CMP_IN_EL1		(GINSENG_TEST | 0x8879)

#define GINSENG_TEST_CLEAR_PAGE_TRACE					(GINSENG_TEST | 0x9977)
#define GINSENG_TEST_CLEAR_PAGE_CLR_IN_EL1_CHECK_IN_EL3	(GINSENG_TEST | 0x9978)
#define GINSENG_TEST_CLEAR_PAGE_CLR_IN_EL3_CHECK_IN_EL1	(GINSENG_TEST | 0x9979)

#define GINSENG_TEST_VMALLOC							(GINSENG_TEST | 0x8888)
#define GINSENG_TEST_SMC_CMD_SET_64BIT_DCI				(GINSENG_TEST | 0x8889)
#define GINSENG_TEST_SMC_CMD_SET_64BIT					(GINSENG_TEST | 0x888A)
#define GINSENG_TEST_MAKE_KERNEL_PFAULT					(GINSENG_TEST | 0x8899)
#define GINSENG_TEST_KERNEL_PTABLE_RO					(GINSENG_TEST | 0x88AA)
#define GINSENG_TEST_EMULE_KERNEL_PTABLE_RO				(GINSENG_TEST | 0x88BB)

#define GINSENG_TEST_PAGETABLE_WALK						(GINSENG_TEST | 0x0001)
#define GINSENG_TEST_PAGETABLE_FIND_PGDIR				(GINSENG_TEST | 0x0002)
#define GINSENG_TEST_PAGETABLE_FIND_PGD_ENTRIES			(GINSENG_TEST | 0x0003)
#define GINSENG_TEST_PAGETABLE_FIND_TABLES				(GINSENG_TEST | 0x0004)
#define GINSENG_TEST_PAGE_OPERATION_EL3					(GINSENG_TEST | 0x0005)
#define GINSENG_TEST_READ_USER_FROM_K					(GINSENG_TEST | 0x0006)
#define GINSENG_TEST_SMC_PING							(GINSENG_TEST | 0x0007)
#define GINSENG_TEST_PAGETABLE_LIVE_TABLES				(GINSENG_TEST | 0x0008)
#define GINSENG_TEST_USER_VADDR_TO_PADDR				(GINSENG_TEST | 0x0009)
#define GINSENG_TEST_SENTRY_VIA_SMC						(GINSENG_TEST | 0x000A)
#define GINSENG_TEST_EL3_PT_WALK						(GINSENG_TEST | 0x000B)
#define GINSENG_TEST_NULL								(GINSENG_TEST | 0x000C)
#define GINSENG_TEST_PAGETABLE_FIND_TABLES_QUIET		(GINSENG_TEST | 0x000D)
#define GINSENG_TEST_PAGETABLE_LIVE_TABLES_QUIET		(GINSENG_TEST | 0x000E)
#define GINSENG_TEST_PAGETABLE_PRINT_PTPBLOCKS			(GINSENG_TEST | 0x000F)
#define GINSENG_TEST_PAGETABLE_FIND_NORMAL_BLOCKS		(GINSENG_TEST | 0x0010)
#define GINSENG_TEST_PAGETABLE_FIND_ALL_BLOCKS			(GINSENG_TEST | 0x0011)
#define GINSENG_TEST_HVC								(GINSENG_TEST | 0x0012)
#define GINSENG_TEST_THREAD_TTBR0_EL1					(GINSENG_TEST | 0x0013)

#define GINSENG_TEST_RS_PING							(GINSENG_TEST | 0x0A00)
#define GINSENG_TEST_RS_NULL							(GINSENG_TEST | 0x0A01)

#define GINSENG_MEASURE									0xAB000000
#define GINSENG_MEASURE_PMRESET							(GINSENG_MEASURE | 0x0001)
#define GINSENG_MEASURE_TRACE_PF						(GINSENG_MEASURE | 0x0002)
#define GINSENG_MEASURE_DONTTRACE_PF					(GINSENG_MEASURE | 0x0003)
#define GINSENG_MEASURE_TRACE_IRQ						(GINSENG_MEASURE | 0x0004)

#endif